name: pdnet
services:
  neo4j:
    image: neo4j:5.20-enterprise
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    # Volumnes to be used need to be customized accordingly, this is just for myself
    volumes:
      - ./data:/var/lib/neo4j/import/
      - D:\Playground\Neo4j\relate-data\dbmss\dbms-2a7a5a8a-3958-474c-817a-30392b43fdf7\data:/var/lib/neo4j/data
      - D:\Playground\Neo4j\relate-data\dbmss\dbms-2a7a5a8a-3958-474c-817a-30392b43fdf7\plugins:/var/lib/neo4j/plugins
    # command: neo4j-admin database load --from=/var/lib/neo4j/import/ pdnet

  nestjs:
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    env_file:
      - backend/.env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5000:80"
