name: pdnet
services:
  neo4j:
    image: neo4j:5.20-enterprise
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4JLABS_PLUGINS='["apoc"]'
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

  nestjs:
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    env_file:
      - .env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:5000"
