name: pdnet
services:
  neo4j:
    image: neo4j:5.20-enterprise
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_transaction_total_max=1024m
    # Volumnes to be used need to be customized accordingly, this is just for myself
    volumes:
      - ./data:/var/lib/neo4j/import/
      - D:\Playground\Neo4j\relate-data\dbmss\dbms-2c9bc5e7-bc36-47de-b509-ab97c052158a\data:/var/lib/neo4j/data
      - D:\Playground\Neo4j\relate-data\dbmss\dbms-2c9bc5e7-bc36-47de-b509-ab97c052158a\plugins:/var/lib/neo4j/plugins
    # command: neo4j-admin database load --from-path=/var/lib/neo4j/import/ pdnet
    # For seeding database

  nestjs:
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    env_file:
      - backend/.env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5000:80"
