name: pdnet
services:
  neo4j:
    image: neo4j:5.20-enterprise
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # - NEO4J_dbms_memory_transaction_total_max=1024m
      # Volumnes to be used need to be customized accordingly, this is just for myself
    volumes:
      - ../data:/var/lib/neo4j/import/
      - ../neo4j/data:/var/lib/neo4j/data
      - ./plugins:/var/lib/neo4j/plugins

  nestjs:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: nestjs
    # Change this if running on local to avoid restarting on failure
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    env_file:
      - backend/.env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5000:80"

  gsea:
    build:
      context: backend/gsea
      dockerfile: Dockerfile
    container_name: gsea
    ports:
      - "8000:8000"
